package_assets:         on
embed_assets:           on
template_function:      _.template
package_path:           bundles
compress_assets:        on
javascript_compressor:  closure
compressor_options:
 # compilation_level: "ADVANCED_OPTIMIZATIONS"

# assets mapping
stylesheets:
  application:
    - public/stylesheets/*.css
    - public/stylesheets/vendor/jquery-ui.css
  mobile_campaign:
    - public/stylesheets/mobcn/*.css
    - public/stylesheets/vendor/fileuploader.css

javascripts:
  application:
    - public/javascripts/vendor/jquery-min.js
    - public/javascripts/vendor/jquery-ui-min.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/smbs.js
    - public/javascripts/analytic/*.js
  admin_dashboard:
    - public/javascripts/admin/*.js
  mobile_campaign_builder:
    - public/javascripts/vendor/inheritance.js
    - public/javascripts/vendor/fileuploader.js
    - public/javascripts/mobcn/builder/partial_behaviour.js
    - public/javascripts/mobcn/builder/images_behaviour.js
    - public/javascripts/mobcn/builder/texts_behaviour.js
    - public/javascripts/mobcn/builder/headers_behaviour.js
    - public/javascripts/mobcn/builder/delimiters_behaviour.js
    - public/javascripts/mobcn/builder/likeits_behaviour.js
    - public/javascripts/mobcn/*.js
